pipeline {
    agent {
        docker {
            image 'maven:3.9.0'  // Use Maven Docker image
            args '-v /root/.m2:/root/.m2'  // Persist Maven dependencies
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'  // Skip tests during build
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'  // Run tests
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'  // Archive test reports
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'  // Run custom deliver script
            }
        }
    }
}
